Netflix <- read.csv("C:/Users/slee2/Downloads/FAANG_Stock_Data/Netflix.csv")
Google <- read.csv("C:/Users/slee2/Downloads/FAANG_Stock_Data/Google.csv")
Facebook <- read.csv("C:/Users/slee2/Downloads/FAANG_Stock_Data/Facebook.csv")
Apple <- read.csv("C:/Users/slee2/Downloads/FAANG_Stock_Data/Apple.csv")
Amazon <- read.csv("C:/Users/slee2/Downloads/FAANG_Stock_Data/Amazon.csv")
plot(strptime(Google$Date, "%m/%d/%Y"), Google$Volume, main="Volume for Google from 2004-2020", xlab="Date", ylab="Volume", las=1, col="DarkGreen", col.lab="Blue", pch=20)
histvalues <- as.numeric(Apple$Close) - as.numeric(Apple$Adj.Close)
hist(histvalues, main="Closing Price minus Adjusted Closing price for Apple", xlab="Difference in Dollars", ylab="Number of Occurrences", col="Yellow")
plot(strptime(Amazon$Date, "%m/%d/%Y"), Amazon$Close, main="Opening Price of FAANG", xlab="Date", ylab="Opeing Price", type="l", las=1, col="2", col.main="Purple")
lines(strptime(Google$Date, "%m/%d/%Y"), Google$Open, type="l", col="3")
lines(strptime(Netflix$Date, "%m/%d/%Y"), Netflix$Open, type="l", col="7")
lines(strptime(Facebook$Date, "%m/%d/%Y"), Facebook$Open, type="l", col="4")
lines(strptime(Apple$Date, "%m/%d/%Y"), Apple$Open, type="l", col="1")
legend(x = "topleft", legend = c("Facebook", "Amazon", "Apple", "Netflix", "Google"), lty = c(1, 1, 1, 1, 1), col = c(4, 2, 1, 7, 3), lwd = 2)